services:
  frontend:
    build: ./frontend
    image: argon/studi-boost/frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    working_dir: /app
    command: ["npm", "run", "dev"]

  backend:
    build: ./backend
    image: argon/studi-boost/backend
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    working_dir: /app
