services:
  frontend:
    build: ./frontend
    image: argon/studi-boost/frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    working_dir: /app
    command: ["npm", "run", "dev"]
